[window]
dimensions = { columns = 120, lines = 75}
decorations = "None"
padding = { x = 8, y = 8 }
dynamic_title = true
opacity = 0.85 # Transparencia para ver a Eevee
blur = true    # Solo funciona en algunos compositores, pero queda pro

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 11.0

[colors.primary]
background = '#241a24' # Tu marr√≥n Sunset
foreground = '#e0d0c0' # Texto claro suave

[colors.normal]
black =   '#1a141a'
red =     '#f44336'
green =   '#4caf50'
yellow =  '#ffeb3b'
blue =    '#2196f3'
magenta = '#9c27b0'
cyan =    '#00bcd4'
white =   '#e0d0c0'

[colors.selection]
text = '#241a24'
background = '#ef955c' # Naranja para selecciones

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block" }
